name: 'Treeless checkout with path'
description: 'Check out a repository with --filter=tree:0'
author: classabbyamp
branding:
  icon: download-cloud
  color: purple
inputs:
  ref:
    description: 'Ref to checkout (SHA, branch, tag)'
    required: false
    default: ${{ github.ref }}
  repository:
    description: 'Repository name'
    required: false
    default: ${{ github.repository }}
  server_url:
    description: 'GitHub server url'
    required: false
    default: ${{ github.server_url }}
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/checkout.sh
      shell: bash
      env:
        GITHUB_REF: ${{ inputs.ref }}
        REPOSITORY: ${{ inputs.repository }}
        SERVER_URL: ${{ inputs.server_url }}
        CLONE_PATH: ${{ inputs.path }}
